### ISSUE TITLE
listtransactions is now totally out of order with 0.0.5 release

### ISSUE THREAD

**Issue by ocminer** [decred/dcrd#65] opened 2016-02-29 12:51 UTC
Since 0.0.5 "listtransactions" not only lists transactions in reverse order, no, it now also lists transactions in totally random order.

As a quick fix I've had to read the results into an array and i'm sorting this array using the "blocktime" field.

**Comment by jcvernaleo** [comment] 2016-03-07 13:30
This issue is a duplicate of #3 (so it is not an 0.0.5 issue but a behavior we've inherited from btcd).  Closing this issue so any discussion takes place all in one place.

**Closed by jcvernaleo** 2016-03-07 13:30 UTC
Labels: duplicate
