### ISSUE TITLE
rpcserver: The searchrawtransactions RPC some issues

### ISSUE THREAD

**Issue by davecgh** [decred/dcrd#186] opened 2016-05-17 22:49 UTC
* The JSON output for coinbases when the `vinPrev` option is set does not include the new Decred-specific fields
* The results are not including entries in the most recent block
* Entries in the mempool do not appear to be ordered correctly with respect to entries already in blocks.  They should be after all entries in blocks when the `reverse` flag is set and before them when it's not.

**Comment by tuxcanfly** [comment] 2016-08-03 15:48
Does `vinPrev` refer to `vinextra` option? If so, we have `PrevOut` key containing `Addresses` and `Value` of the previous output. What specific fields do we need here?

**Comment by tuxcanfly** [comment] 2016-08-03 18:20
I was able to search tx from the best block so I was not able to reproduce the second point if it persists. Still checking to make sure I'm not missing any case.

As for the third point, by default (i.e `reverse` false) the transactions seem to be ordered oldest first i.e most confirmations to least. I'd assume in such a case it makes sense to have mempool transactions last  as they have zero confirmations. Vice versa, with `reverse` true, mempool transactions appear first and the rest of the transactions follow from least to most confirmations. This is how it is currently implemented.

**Comment by davecgh** [comment] 2016-08-03 18:37
As the issue title says, this has to do with the results from `searchrawtransactions`.  In particular, the `createVinListPrevOut` function which returns `[]dcrjson.VinPrevOut`.  That structure should be properly filled out when dealing with coinbase transactions and it's currently not.

For example, it's only setting the `Coinbase` and `Sequence` fields right now and should also be setting the other new Decred fields such as `BlockHeight`, `BlockIndex` and `PrevOut` (when the `vinExtra` flag is set).

**Comment by davecgh** [comment] 2016-08-03 18:40
The third point might have been fixed by later commits since this issue was created.  It will require thorough testing to ensure it's working properly now.

**Comment by tuxcanfly** [comment] 2016-08-04 16:44
Since it's a `Coinbase` transaction, and the `BlockIndex`, `BlockHeight` refer to the index and height of the origin transaction, I think they are not relevant. I found `Amount` to be the only relevant field that could be added.

**Comment by tuxcanfly** [comment] 2016-08-05 12:06
After testing a while I was able to find instances where a regular unconfirmed transaction is missing from the searchrawtransaction output even though it was present in the latest block. This seemed to happen with relatively new addresses so I think it might have to do with the address indexer not catching up rather than the RPC call.

**Comment by tuxcanfly** [comment] 2016-08-10 16:49
The second point, i.e not including entries for most recent block might happen if the tx is missing in the node's mempool and is not yet confirmed.

**Comment by alexlyp** [comment] 2016-08-10 16:53
#299 merged

**Closed by alexlyp** 2016-08-10 16:53 UTC
Labels: bug
