### ISSUE TITLE
Strange mempool reactions to SStx (fees and predictive confirmations)

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrd#15] opened 2016-02-10 17:00 UTC
bug report from Skarsol in #decred: I can predict, +-1 block (usually exactly) when my transaction will be confirmed. It's also no respecting the fees. I can get confirmations (regularly) with .001 fee while a manually sent .07 will never confirm.

Fees don't appear to effect priority and sstx confirmations are some how predictive?

**Comment by cjepson** [comment] 2016-02-10 17:07
I'll look into it. Fees sorting and this mining code was an area tagged for clean up and refactor before release. It should finally be fixed up and proper settxfee/gettxfee for wallet and daemon implemented.

**Comment by chappjc** [comment] 2016-02-19 05:25
It's hard to decide if I should stake more DCR at this point with an increased tx fee.  If the higher fee doesn't matter, why commit to it?  Is the root cause of this issue clear?  Thanks, @cjepson .

**Comment by cjepson** [comment] 2016-04-13 21:00
Fixed in #113

**Closed** 2016-04-20 21:01 UTC
Labels: bug
