### ISSUE TITLE
Ban on wire protocol error[s]

### ISSUE THREAD

**Issue by dajohi** [decred/dcrd#350] opened 2016-09-20 16:51 UTC
We should ban peers that do not follow the wire protocol.

**Comment by chappjc** [comment] 2016-09-20 17:05
Oh you mean like payload too large? Yes please.

**Comment by davecgh** [comment] 2016-09-20 17:57
As previously discussed, I'm am 100% favor of being extremely strict with peers in regards to the protocol.

Since it is over TCP, there is no reason for messages that don't follow the spec.  Peers already negotiate a protocol version at start up, so there is really no reason whatsoever they should not be following the protocol spec exactly.  Failure to do so should be banned with prejudice in my opinion.  To clarify, this would include anything from payloads that are too large as mentioned by @chappjc to including more items in `invvect` than is allowed in messages such as `inv` and ` getheaders`.

There are a couple of exceptions that I would like to point out however that would require whitelisting as proposed by #351.  In particular, those are regression tests and local development.

In the case of regression tests, their entire point of existence is to _intentionally_ try to send malformed data and verify they are disconnected.  Banning them for it would not allow multiple cases to be properly tested and as such 127.0.0.1 would need to be whitelisted during said tests.

For the second case of local development, when developers are attempting to add a new protocol message, or even develop their own libraries (say for example to be able to connect from another language), being banned from their local node as they work through the development would not be ideal.  Once again, allowing them to whitelist their local node would cleanly resolve that case.

**Comment by alexlyp** [comment] 2016-11-03 17:53
So this issue is waiting for #351 PR to be synced in btcd upstream, then once that is in we can start to develop a list of bannable protocol errors

**Comment by davecgh** [comment] 2020-05-06 19:28
This will be resolved when #2110 lands.

**Comment by davecgh** [comment] 2020-05-11 00:08
Resolved by #2110.

**Closed by davecgh** 2020-05-11 00:08 UTC
Labels: enhancement
