### ISSUE TITLE
Crazy TX fees per Transaction

### ISSUE THREAD

**Issue by ocminer** [decred/dcrd#50] opened 2016-02-23 14:53 UTC
sendtoaddress Dxxx2 1.25
-32603: insufficient funds: transaction requires 1.4 Coin input (1.25 Coin output + 0.15 Coin fee) but only 1.30419483 Coin spendable

 "balance": 95.77621107

1. Waiting and retrying after a few blocks helps mostly for sending even though I have > 95 coins in balance - this is not how it is supposed to work.

2. The crazy TX fee still remains, how can I send 1.25 coins but need to pay 0.15 coins in fee, this is totally crazy for one single transaction.

**Comment by cjepson** [comment] 2016-02-25 02:09
Hey, this bug is caused by a dusting wallet. We're working on trying to figure out better fee estimation algorithms, because the current one is very dumb. In the event there are not amounts for fees, it should record the number of UTXOs it first got and then recalculate fees. Then it should pull a larger number of UTXOs and try again. The quick workaround is to send all funds to yourself and then send to the recipient.

**Comment by cjepson** [comment] 2016-04-18 17:31
Fixed in latest wallet.

**Closed by cjepson** 2016-04-18 17:31 UTC
Labels: bug

**Comment by raedah** [comment] 2016-04-18 17:33
Which PR is this fixed in?
