### ISSUE TITLE
Max peers settings doesn't look it works

### ISSUE THREAD

**Issue by dema501** [decred/dcrd#2691] opened 2021-07-31 11:58 UTC
I have dcrd.conf

```
; Maximum number of inbound and outbound peers.
maxpeers=16

;
addpeer=xx1.xx1.xx1.xx1:9108
addpeer=xx2.xx2.xx2.xx2:9108
addpeer=xx3.xx3.xx3.xx3:9108
addpeer=xx4.xx4.xx4.xx3:9108
addpeer=xx5.xx5.xx5.xx4:9108
```
when I run:
dcrctl  getpeerinfo | grep -c '"addr"'
```
"addr": "xx1.xx1.xx1.xx1:9108",
"addr": "xx2.xx2.xx2.xx2:9108",
"addr": "xx3.xx3.xx3.xx3:9108",
"addr": "xx4.xx4.xx4.xx3:9108",
"addr": "xx5.xx5.xx5.xx4:9108",
...
3 more peer node 
```

It doesn't matter how many times I run `dcrctl  getpeerinfo` it always gives me 8 total 

dcrd -V
dcrd version 1.6.2+release (Go version go1.16.4 freebsd/amd64)

**Comment by davecgh** [comment] 2021-07-31 13:13
The maximum number of **outbound** peers is locked to 8.  Increasing the `maxpeers` parameter above that only allows more **inbound** peers.

The number of outbound is locked to 8 because any number higher than that does not help your node while simultaneously taking valuable inbound slots away from other peers.

**Comment by davecgh** [comment] 2021-07-31 13:25
Closing because it's working as intended as previously described.

**Closed by davecgh** 2021-07-31 13:25 UTC
